version: "3"
services:
  web:
    build: .
    environment:
      RAILS_ENV: "development"
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "3001"]
    ports:
      - "3001:3001"
    volumes:
      - ./mv_wall:/mv_wall
